export interface LibraryImage {
  filename: string;
  label?: string;
  category: string;
}

export function libraryImageUrl(filename: string) {
  return `${import.meta.env.BASE_URL}library/${filename}`;
}

export const IMAGE_LIBRARY: LibraryImage[] = [
  // ─── SMB — Candles ───────────────────────────────────────────────────────────
  { category: "SMB · Candles", filename: "SMB/2024.12.19.Candles_0200.jpg", label: "Woman reaching for colorful handmade candles on wooden display shelves" },
  { category: "SMB · Candles", filename: "SMB/2024.12.19.Candles_0463.jpg", label: "Candle maker packing shipping boxes at workbench with colorful candles behind" },
  { category: "SMB · Candles", filename: "SMB/2024.12.19.Candles_0578.jpg", label: "Close-up of hands cutting packing tape on a cardboard box with brass scissors" },
  { category: "SMB · Candles", filename: "SMB/2024.12.19.Candles_0743.jpg", label: "Woman adjusting a candle-dipping rack with wicks hanging down" },
  { category: "SMB · Candles", filename: "SMB/2024.12.19.Candles_1405.jpg", label: "Woman dipping taper candles into a large wax vat in her workshop" },
  { category: "SMB · Candles", filename: "SMB/2024.12.19.Candles_1709.jpg", label: "Hand selecting green taper candles hanging on hooks on wooden shelving" },

  // ─── SMB — Skate Shop ────────────────────────────────────────────────────────
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_0035.jpg", label: "Wall-mounted rack filled with rows of skateboard decks on display" },
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_0086.jpg", label: "Man shaping a skateboard deck on a belt sander in his workshop" },
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_0165.jpg", label: "Close-up of man cutting a skateboard deck shape on a red bandsaw" },
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_0303.jpg", label: "Tattooed hands using a router to shape a raw wood skateboard deck" },
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_0784.jpg", label: "Man sanding a skateboard deck on a workbench" },
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_0839.jpg", label: "Skate shop maker holding a paint roller beside a skateboard deck" },
  { category: "SMB · Skate Shop", filename: "SMB/2024.12.19.Skate.Shop_1275.jpg", label: "Tattooed hand holding a finished painted skateboard with colorful graphic art" },

  // ─── SMB — Shoot 01 ──────────────────────────────────────────────────────────
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_814.jpg",  label: "Woman shaping a clay vessel on a pottery wheel in her studio" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_1357.jpg", label: "Overhead view of ceramic cups, brushes, and sponges on a striped towel" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_1837.jpg", label: "Smiling woman holding up a red and white checkered ceramic cup" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_1856.jpg", label: "Hands detailing a pink checkered pattern on a ceramic cup at workbench" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_2309.jpg", label: "Woman packing a blue grid-patterned mug into a shipping box with laptop nearby" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_2793.jpg", label: "Woman arranging handmade ceramic cups and bowls on wooden display shelves" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_3153.jpg", label: "Close-up of hands painting a pink checkered pattern on a ceramic piece" },
  { category: "SMB · Shoot 01", filename: "SMB/241121_SR_PAYPAL_SHOT_01_3762.jpg", label: "Woman carrying stacked shipping boxes while checking her phone in hallway" },

  // ─── SMB — UK CS ─────────────────────────────────────────────────────────────
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_271.jpg",  label: "Two people in aprons holding a large red poppy-shaped tufted rug" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_1704.jpg", label: "Woman in apron displaying a handmade blue floral tufted rug" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_1713.jpg", label: "Close-up of hands holding a large spool of blue yarn" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_1825.jpg", label: "Two people selecting colorful yarn spools from shelves with a tablet" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_1877.jpg", label: "Woman in apron pulling blue yarn from a shelf spool" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_1937.jpg", label: "Woman seated using a tufting gun with colorful yarn shelves behind" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_1973.jpg", label: "Two people in aprons pouring adhesive onto fabric in a textile workshop" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_2004.jpg", label: "Close-up of hand spreading glue on tufted rug backing with a scraper" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_2021.jpg", label: "Hands using an electric trimmer to shear a blue floral tufted rug" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_2138.jpg", label: "Woman using a tufting gun on a floral design canvas in a studio" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_2252.jpg", label: "Close-up of a tufting gun adding blue yarn to a floral pattern canvas" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_001_2345.jpg", label: "Man in apron holding a tufting gun near yarn shelves" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_002_034.jpg",  label: "Man trimming edges of a textured handmade rug piece with scissors" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_002_151.jpg",  label: "Person carrying a box past colorful yarn shelves in a workshop" },
  { category: "SMB · UK CS", filename: "SMB/241211_PAYPAL_UK_CS_003_086.jpg",  label: "Shelves stacked with blue and grey yarn spools in various shades" },

  // ─── SMB — UK PCL ────────────────────────────────────────────────────────────
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_001_003.jpg", label: "Overhead view of open paint pots and brushes on a messy worktable" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_001_087.jpg", label: "Colorful paint swatches daubed in overlapping circles on a board" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_001_109.jpg", label: "Studio wall covered with colorful art prints, posters, and illustrations" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_001_118.jpg", label: "Stacked cardboard shipping tubes labeled Print Club London on a shelf" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_002_011.jpg", label: "Man in paint-splattered apron preparing a screen printing frame" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_002_062.jpg", label: "Person holding Print Club London branded tape near a screen printing press" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_003_050.jpg", label: "Colorful screen-printed LOVE typographic art prints on a drying rack" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_003_147.jpg", label: "Person applying blue ink to a green screen printing frame" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_003_559.jpg", label: "Woman operating a large screen printing press with squeegee mechanism" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_070.jpg", label: "Person holding up a blue All Night Long screen print against a shutter" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_097.jpg", label: "Woman holding print outside Print Club London entrance" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_115.jpg", label: "Artist working at a desk in a bright studio filled with colorful prints" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_127.jpg", label: "Artist using a stylus on a digital drawing tablet at her desk" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_220.jpg", label: "Smiling artist in overalls posing with digital tablet showing lettering design" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_304.jpg", label: "Close-up of hand drawing blue lettering on paper with a marker pen" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_374.jpg", label: "Two artists collaborating over print designs at a sunlit studio table" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_423.jpg", label: "Artist sketching blue hand-lettered typographic designs on paper" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_437.jpg", label: "Two people reviewing illustrated print artwork and sketches on a table" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_004_508.jpg", label: "Two artists smiling and reviewing print proofs in a bright creative studio" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_005_427.jpg", label: "Two people packing and organizing prints with shipping tubes in storage" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_005_467.jpg", label: "Woman reaching into flat file shelves to retrieve stored art prints" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_005_517.jpg", label: "Person rolling up a colorful LOVE print next to a Print Club London box" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_005_615.jpg", label: "Hands packaging a print into a cardboard mailer labeled Print Club London" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_005_749.jpg", label: "Woman standing and smiling in a print storage room with flat file shelves" },
  { category: "SMB · UK PCL", filename: "SMB/241211_PAYPAL_UK_PCL_005_761.jpg", label: "Woman leaning on a table posing in front of flat file print storage shelves" },

  // ─── SMB — Pasta Shop ────────────────────────────────────────────────────────
  { category: "SMB · Pasta Shop", filename: "SMB/PAYPAL DAY 01 SMB PASTA SHOP 0372 f1.jpg", label: "Chef holding a fresh sheet of pasta dough above a pasta machine" },
  { category: "SMB · Pasta Shop", filename: "SMB/PAYPAL DAY 01 SMB PASTA SHOP 0796 f1.jpg", label: "Smiling woman cutting fresh pasta dough on a wooden board in a rustic kitchen" },

  // ─── Tap to Pay ──────────────────────────────────────────────────────────────
  { category: "Tap to Pay", filename: "TapToPay/mkt-us-page-tap-to-pay-component-stack-section-1-size-tablet-up.jpg", label: "Two phones tapping together for contactless payment at a bakery stand" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_3895_ALT_V2.jpg", label: "Hand holding phone with PayPal card near a card reader in clothing store" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_4091.jpg",        label: "Top-down view of phone tapping PayPal card on card reader, marble surface" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_4093.jpg",        label: "Top-down view of phone with PayPal card hovering over card reader" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_4137.jpg",        label: "Hand tapping phone with PayPal toward a card reader on marble counter" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_4198.jpg",        label: "Close-up of phone with PayPal card held near card reader, white background" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_4243.jpg",        label: "Close-up of phone with PayPal card approaching card reader from above" },
  { category: "Tap to Pay", filename: "TapToPay/TTP_Studio_4386.jpg",        label: "Hand holding phone with PayPal card over black card reader on wood surface" },

  // ─── Other ───────────────────────────────────────────────────────────────────
  { category: "Other", filename: "Other/audience-component-story-scroll-1-size-tablet-up.jpg",                label: "Man working on tablet at desk with PayPal shield icon overlay" },
  { category: "Other", filename: "Other/card-wrapped-tools-2_size-all.jpg",                                   label: "Man in apron packing items into a shipping box in colorful warehouse" },
  { category: "Other", filename: "Other/feature-column-split-section_size-all.jpg",                            label: "Smiling woman inspecting an unfinished ceramic cup in pottery studio" },
  { category: "Other", filename: "Other/mkt-us-page-tap-to-pay-component-stack-section-2-size-tablet-up.jpg", label: "Two people outdoors with phone showing payment methods screen" },
  { category: "Other", filename: "Other/solopreneur-component-card-wrapped-payments-3-size-all.jpg",           label: "Credit card tapping on phone showing $35 payment for City Ceramics" },
  { category: "Other", filename: "Other/us-business-debit-card-product-value-section-1-all-updated.jpg",        label: "Hand holding phone with PayPal Business Debit card near card reader" },
  { category: "Other", filename: "Other/videoframe_1252.jpg",                                                   label: "Hands painting a red-and-pink striped ceramic cup at craft workbench" },
  { category: "Other", filename: "Other/videoframe_4027.jpg",                                                   label: "Woman walking five dogs on leashes in a sunny park" },

  // ─── BDMC 2025 ───────────────────────────────────────────────────────────────
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202526530.jpg",        label: "Hand holding up PayPal Business Debit card against light blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202526580.jpg",        label: "Hand holding up tilted PayPal Business Debit card against blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202527210.jpg",        label: "Hand holding PayPal Business Debit card with gray text on blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202527460.jpg",        label: "Two hands each holding a PayPal Business Debit card against blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202527490.jpg",        label: "Two hands holding PayPal Business Debit cards at different angles, blue" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202528550.jpg",        label: "PayPal Business Debit card resting on edge of white block, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202528670.jpg",        label: "PayPal Business Debit card angled on white pedestal, gray background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 20252883 10.jpg",      label: "Three PayPal Business Debit cards fanned out on white blocks, gray background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202528830.jpg",        label: "Three PayPal Business Debit cards fanned out on white blocks, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202529130.jpg",        label: "Two PayPal Business Debit cards propped on cylindrical stands, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202529200.jpg",        label: "PayPal Business Debit card leaning on cylindrical props on blue pedestal" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202529500.jpg",        label: "Hand holding PayPal Business Debit card above black card reader, gray background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202529510.jpg",        label: "Hand inserting PayPal Business Debit card into black card reader, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202529800.jpg",        label: "Hand tapping PayPal Business Debit card on black card reader, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202529970_v02.jpg",    label: "Hand holding phone with PayPal wallet near black card reader, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202530100_v02.jpg",    label: "Hand tapping phone with PayPal wallet on black card reader, blue background" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC 202530190.jpg",        label: "PayPal Business Debit card floating at angle against light blue backdrop" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_30400.jpg",       label: "Person tucking PayPal Business Debit card into denim jacket breast pocket" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_30760.jpg",       label: "Person sliding PayPal Business Debit card into paint-splattered pants pocket" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_31170.jpg",       label: "Person holding PayPal card and wallet at cafe counter with card reader" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_31620.jpg",       label: "Customer tapping PayPal card on white reader at cafe with croissant visible" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_3173_chip_v01.jpg", label: "Customer handing PayPal card to cashier over black reader at cafe counter" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_31810.jpg",       label: "Customer tapping PayPal card on black reader at cafe, coffee cups visible" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_31810 (1).jpg",   label: "Customer tapping PayPal card on black reader at cafe, alternate angle" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_32490.jpg",       label: "PayPal Business Debit card on orange desk mat with keyboard and plants" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_32490 (1).jpg",   label: "PayPal Business Debit card on orange desk mat with office supplies" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_32700.jpg",       label: "PayPal Business Debit card on notebooks atop yellow desk mat" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_32700 (1).jpg",   label: "PayPal Business Debit card on notebooks with office supplies, alternate" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_32860_v02.jpg",   label: "Phone showing PayPal wallet on blue desk mat with keyboard and stationery" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_32910.jpg",       label: "Hand holding PayPal Business Debit card over blue desk mat with supplies" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_33160.jpg",       label: "Two hands exchanging PayPal Business Debit card over wooden desk" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_33160 (1).jpg",   label: "Two hands exchanging PayPal Business Debit card, alternate angle" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_33160 (2).jpg",   label: "Two hands exchanging PayPal Business Debit card, wide angle" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_33220.jpg",       label: "Hand tapping PayPal card toward black card reader on wooden table with coffee" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_33450.jpg",       label: "Hand tapping PayPal card on white card reader with green coffee mug" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_45780.jpg",       label: "Hand holding PayPal Business Debit card at ATM with wallet, green sleeves" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_45780 (1).jpg",   label: "Hand holding PayPal Business Debit card at ATM, alternate angle" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46040.jpg",       label: "Hand inserting PayPal Business Debit card into ATM with yellow wallet" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46070.jpg",       label: "Close-up of hand inserting PayPal Business Debit card into ATM slot" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46200.jpg",       label: "Hand inserting PayPal card into ATM showing receipt printer" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46520.jpg",       label: "Hand holding PayPal Business Debit card at cafe table with croissant" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46600.jpg",       label: "Close-up of hand holding PayPal Business Debit card with receipt and coffee" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46730_v02.jpg",   label: "Hand holding phone showing PayPal wallet at cafe with croissant and coffee" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46910_v02.jpg",   label: "Phone with PayPal wallet on table beside receipt, coffee, and croissant" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_46960_v02.jpg",   label: "Top-down of phone with PayPal wallet beside receipt, coffee, and croissant" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47140.jpg",       label: "Hand holding PayPal card with wallet at cafe, sunglasses and coffee visible" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47320.jpg",       label: "Hand holding PayPal card above wallet at cafe table with coffee and notebook" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47370.jpg",       label: "PayPal Business Debit card resting on brown leather wallet on cafe table" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47460.jpg",       label: "PayPal Business Debit card on leather wallet beside sunglasses and coffee" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47610.jpg",       label: "PayPal Business Debit card on clipboard with receipt and pen on wooden table" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47680.jpg",       label: "Hand placing PayPal card on table next to receipt clipboard and coffee" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_47810.jpg",       label: "Person holding PayPal card and coffee mug at table with receipt clipboard" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_48090.jpg",       label: "Person pulling PayPal Business Debit card from floral-patterned wallet" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_49450.jpg",       label: "Two hands exchanging PayPal Business Debit card over shipping boxes" },
  { category: "BDMC 2025", filename: "BDMC-2025/BDMC_2025_49680_v02.jpg",   label: "Hands holding phone with PayPal wallet and card reader over shipping boxes" },
];

/** All unique category names, in the order they first appear */
export const IMAGE_CATEGORIES = [...new Set(IMAGE_LIBRARY.map((img) => img.category))];
